### ISSUE TITLE
user-friendly error messages: Unused import "___"

### ISSUE THREAD

**Issue by mitchtbaum** [buildinspace/peru#106]
I made a simple mistake and misnamed my module's import name:

```
imports:
  plugin: plugins/

git module plugins:
    url: https://github.com/mitchtbaum/pelican_reference.git
```

(It should have been 'git module plugin', singular.)

I believe this made Peru crash since it tried to process an import without any modules, and so Peru showed me a scary traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/peru", line 9, in <module>
    load_entry_point('peru==0.2.0', 'console_scripts', 'peru')()
  File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 161, in main
    Main().run(argv, env)
  File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 79, in run
    async.run_task(matching_command(self))
  File "/usr/local/lib/python3.4/dist-packages/peru/async.py", line 25, in run_task
    return asyncio.get_event_loop().run_until_complete(coro)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 298, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 90, in do_sync
    self.runtime, self.scope, self.imports, self.runtime.root)
  File "/usr/local/lib/python3.4/dist-packages/peru/imports.py", line 11, in checkout
    imports_tree = yield from get_imports_tree(runtime, scope, imports)
  File "/usr/local/lib/python3.4/dist-packages/peru/imports.py", line 20, in get_imports_tree
    target_trees = yield from get_trees(runtime, scope, imports.keys())
  File "/usr/local/lib/python3.4/dist-packages/peru/imports.py", line 29, in get_trees
    trees = yield from stable_gather(*futures)
  File "/usr/lib/python3.4/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 351, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/peru/imports.py", line 35, in get_tree
    module, rules = yield from scope.parse_target(runtime, target_str)
  File "/usr/local/lib/python3.4/dist-packages/peru/scope.py", line 26, in parse_target
    runtime, pipeline_parts[0], target_str)
  File "/usr/local/lib/python3.4/dist-packages/peru/scope.py", line 36, in resolve_module
    runtime, module_names, logging_target_name))
  File "/usr/local/lib/python3.4/dist-packages/peru/scope.py", line 41, in _resolve_module_from_names
    next_module = self.modules[module_names[0]]
KeyError: 'plugin'
```

Perhaps a single line output (from a non-fatal error?) with something like, ```Unused import 'plugin'```, would make Peru friendler to novice users.

Thank you for Peru.

**Comment by oconnor663** [comment]
Good catch, and thanks for reporting. We've been pretty lax so far with our
error handling in general, so I bet a lot of people are having crappy
experiences like this. Should be easy to print out a more helpful message
in this case.
