### ISSUE TITLE
something is hosing AppVeyor tests

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#140]
```
======================================================================
ERROR: test_curl_plugin_reup (test_plugins.PluginsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\peru\tests\test_plugins.py", line 277, in test_curl_plugin_reup
    self.plugin_context, 'curl', fields)
  File "C:\projects\peru\tests\test_plugins.py", line 36, in test_plugin_get_reup_fields
    plugin.plugin_get_reup_fields(context, type, fields, handle))
  File "C:\projects\peru\peru\async.py", line 25, in run_task
    return asyncio.get_event_loop().run_until_complete(coro)
  File "C:\Python33\lib\site-packages\asyncio\base_events.py", line 316, in run_until_complete
    return future.result()
  File "C:\Python33\lib\site-packages\asyncio\futures.py", line 275, in result
    raise self._exception
  File "C:\Python33\lib\site-packages\asyncio\tasks.py", line 236, in _step
    result = coro.send(value)
  File "C:\Python33\lib\site-packages\asyncio\coroutines.py", line 92, in send
    return self.gen.send(value)
  File "C:\projects\peru\peru\plugin.py", line 50, in plugin_get_reup_fields
    with open(output_path) as output_file:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\peru\\test\\tmp6jiq7y\\tmpl530v1\\reup_output'
```

Etc.

**Comment by oconnor663** [comment]
Ok, an improvement: some of the tests were failing to start because PyYAML wouldn't build. Fixed that with 107cc0790c41481a7f5b986ef16348ba5daeaeaf. My fault for leaving that script out.

**Comment by oconnor663** [comment]
It looks like most of the tests are failing because we aren't actually shelling out to plugin scripts at all. Something about Python files not being registered with the shell? Need to come up with a way to detect that.

**Comment by oconnor663** [comment]
OK, this is turning out to be very hard to configure properly. I need to make a little hello world AppVeyor project that does nothing but execute a little script and check the interpreter path.

**Comment by oconnor663** [comment]
Could be relevant: http://stackoverflow.com/a/1936078/823869

**Comment by oconnor663** [comment]
Definitely relevant: http://help.appveyor.com/discussions/problems/2569-latest-appveyor-build-platform-update-introduced-a-python-problem

**Comment by oconnor663** [comment]
Finally fixed: https://github.com/buildinspace/peru/commit/1290909d6661941a9ccf1ad85a8cf54f19667ce4

**Comment by oconnor663** [comment]
Oops, looks like the [latest AppVeyor change](http://help.appveyor.com/discussions/problems/2569-latest-appveyor-build-platform-update-introduced-a-python-problem#comment_38755488) re-broke the tests :(

**Comment by oconnor663** [comment]
Fixed this a while ago.
