### ISSUE TITLE
Cannot recover from accidentally running without git

### ISSUE THREAD

**Issue by edbrannin** [buildinspace/peru#147]
## Steps to reproduce:

1. Get a new PC
2. Install Python & Peru
3. Forget to install git
4. Clone a peru-enabled repository
5. Run `peru sync`
6. Install git
7. Run `peru sync`

## Expected result:

* Step 5 fails at cache-setup and stops before trying to clone everything(?)
* Step 7 notices `.peru/cache/trees` is empty, removes it and tries again (successfully).

## Observed result:

* Step 5 fails with [sorry, I didn't capture this] and a huge bunch of stack traces per #134
* Step 7 fails with this at the top, then spews a similar bunch of stack traces as each clone also fails:
* Repeating Step 7 works after I manually `rmdir .peru/cache/tree`

```
C:\dev\dotfiles>peru sync
Traceback (most recent call last):
  File "C:\Python35-32\Scripts\peru-script.py", line 9, in <module>
    load_entry_point('peru==0.3.2', 'console_scripts', 'peru')()
  File "c:\python35-32\lib\site-packages\peru\main.py", line 345, in main
    async.run_task(command_fn(params))
  File "c:\python35-32\lib\site-packages\peru\async.py", line 25, in run_task
    return asyncio.get_event_loop().run_until_complete(coro)
  File "c:\python35-32\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "c:\python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python35-32\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "c:\python35-32\lib\site-packages\peru\main.py", line 91, in do_sync
    params.runtime, params.scope, params.imports, params.runtime.sync_dir)
  File "c:\python35-32\lib\site-packages\peru\imports.py", line 13, in checkout
    imports_tree = yield from get_imports_tree(runtime, scope, imports)
  File "c:\python35-32\lib\site-packages\peru\imports.py", line 24, in get_imports_tree
    target_trees = yield from get_trees(runtime, scope, imports.keys())
  File "c:\python35-32\lib\site-packages\peru\imports.py", line 33, in get_trees
    trees = yield from stable_gather(*futures)
  File "c:\python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "c:\python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "c:\python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\python35-32\lib\site-packages\peru\imports.py", line 42, in get_tree
    tree = yield from module.get_tree(runtime)
  File "c:\python35-32\lib\site-packages\peru\module.py", line 79, in get_tree
    base_tree = yield from self._get_base_tree(runtime)
  File "c:\python35-32\lib\site-packages\peru\module.py", line 70, in _get_base_tree
    tree = yield from runtime.cache.import_tree(tmp_dir)
  File "c:\python35-32\lib\site-packages\peru\cache.py", line 308, in import_tree
    yield from session.read_working_copy_into_index(picks)
  File "c:\python35-32\lib\site-packages\peru\cache.py", line 122, in read_working_copy_into_index
    yield from self.git('add', '--all', '--force')
  File "c:\python35-32\lib\site-packages\peru\cache.py", line 77, in git
    raise GitError(command, process.returncode, stdout, stderr)
peru.cache.GitError: git command "['git', '--git-dir=C:\\dev\\dotfiles\\.peru\\cache\\trees', '--work-tree=C:\\dev\\dotfiles\\.peru\\tmp\\tmpsbbx5pug', 'add', '--all', '--force']" returned error code 128.
stdout:
stderr: fatal: Not a git repository: 'C:\dev\dotfiles\.peru\cache\trees'
```

**Comment by oconnor663** [comment]
Oh dang, thanks for the report. Here's the Step 5 stacktrace I see when I do this in a docker without git:

```
Traceback (most recent call last):
  File "/usr/local/bin/peru", line 9, in <module>
    load_entry_point('peru==0.3.2', 'console_scripts', 'peru')()
  File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 339, in main
    runtime = async.run_task(Runtime(args, env))
  File "/usr/local/lib/python3.4/dist-packages/peru/async.py", line 25, in run_task
    return asyncio.get_event_loop().run_until_complete(coro)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/peru/runtime.py", line 20, in Runtime
    yield from r._init_cache()
  File "/usr/local/lib/python3.4/dist-packages/peru/runtime.py", line 62, in _init_cache
    self.cache = yield from cache.Cache(self.cache_dir)
  File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 250, in Cache
    yield from cache._init_trees()
  File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 271, in _init_trees
    yield from session.init_git_dir()
  File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 93, in init_git_dir
    yield from self.git('init', '--bare')
  File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 70, in git
    stderr=asyncio.subprocess.PIPE)
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 214, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 944, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 183, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 634, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

**Comment by oconnor663** [comment]
Simple fix :) Thanks again for reporting! Really good find.
