### ISSUE TITLE
Opaque stacktrace on Windows when git isn't on PATH

### ISSUE THREAD

**Issue by edbrannin** [buildinspace/peru#175]
This happens when I run `peru sync` on a system without git installed properly (whoops):

```
C:\dev\dotfiles>peru sync
Traceback (most recent call last):
  File "C:\Python36\Scripts\peru-script.py", line 11, in <module>
    load_entry_point('peru==1.1.0', 'console_scripts', 'peru')()
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\main.py", line 370, in main
    run_task(command_fn(params))
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\async_helpers.py", line 29, in run_task
    return asyncio.get_event_loop().run_until_complete(coro)
  File "C:\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\main.py", line 94, in do_sync
    params.runtime, params.scope, params.imports, params.runtime.sync_dir)
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\imports.py", line 18, in checkout
    previous_index_file=index)
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\cache.py", line 379, in export_tree
    previous_tree)
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\cache.py", line 102, in read_tree_and_stats_into_index
    yield from self.read_tree_into_index(tree)
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\cache.py", line 98, in read_tree_into_index
    yield from self.git('read-tree', tree)
  File "C:\Python36\lib\site-packages\peru-1.1.0-py3.6.egg\peru\cache.py", line 71, in git
    stderr=asyncio.subprocess.PIPE)
  File "C:\Python36\lib\asyncio\subprocess.py", line 212, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "C:\Python36\lib\asyncio\base_events.py", line 1190, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Python36\lib\asyncio\windows_events.py", line 378, in _make_subprocess_transport
    **kwargs)
  File "C:\Python36\lib\asyncio\base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "C:\Python36\lib\asyncio\windows_events.py", line 762, in _start
    bufsize=bufsize, **kwargs)
  File "C:\Python36\lib\asyncio\windows_utils.py", line 205, in __init__
    stderr=stderr_wfd, **kwds)
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I had to find `File "....peru\cache.py", line 71, in git` in the middle of the stack trace to know what was going wrong.

**Comment by oconnor663** [comment]
We should just check for git during startup and print a nice message if it's missing.

**Comment by edbrannin** [comment]
...unless somebody's only using mercurial?

**Comment by edbrannin** [comment]
(Actually, the issue exists for both programs)

**Comment by oconnor663** [comment]
Ah good point, we should really clean up both types of errors. The git one is more fundamental, because peru uses git internally to move trees around no matter that module types you're using, while hg only comes up if you actually have an hg module.
