### ISSUE TITLE
Exception from get_tree on Windows

### ISSUE THREAD

**Issue by edbrannin** [buildinspace/peru#69]
I'm getting this error when I try to `peru sync` my dotfiles on my Windows PC:

```
C:\dev\dotfiles>\Python34\Scripts\peru.exe sync
hg plugin exited with error code 1.
Fields:
    rev: edcdb7620f4d4a82d2c936131d319e62198a6e05
    url: ssh://hg@bitbucket.org/durin42/hg-git
Output:
hg pull ssh://hg@bitbucket.org/durin42/hg-git
*** failed to import extension hgbb from $HOME/dev/dotfiles/hg/hgbb/hgbb.py: No module named httprepo
abort: repository default not found!
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resources\plugins\hg\hg_plugin.py", line 108, in <module>
    plugin_fetch()
  File "C:\Python34\lib\site-packages\peru\resources\plugins\hg\hg_plugin.py", line 89, in plugin_fetch
    hg_pull(URL, CACHE_PATH)
  File "C:\Python34\lib\site-packages\peru\resources\plugins\hg\hg_plugin.py", line 67, in hg_pull
    hg('pull', hg_dir=repo_path)
  File "C:\Python34\lib\site-packages\peru\resources\plugins\hg\hg_plugin.py", line 35, in hg
    output))
RuntimeError: Command exited with error code 255:
$ hg --repository C:\dev\dotfiles\.peru\cache\plugins\hg\a7567368584c40ffdd77a772380733a662a5e9b6 pull
None
Exception ignored in: <generator object get_tree at 0x02B21D28>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpm8hm78ys'
Exception ignored in: <generator object get_tree at 0x02B21148>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmphb5ydz9c'
Exception ignored in: <generator object get_tree at 0x02B21A30>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpyfd112fc'
Exception ignored in: <generator object get_tree at 0x02B21210>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpz1jcypzs'
Exception ignored in: <generator object get_tree at 0x02B213C8>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmp8ph5ic9c'
Exception ignored in: <generator object get_tree at 0x02B21BC0>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmp4vuorn6z'
Exception ignored in: <generator object get_tree at 0x02B21B98>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpms15tmqg'
Exception ignored in: <generator object get_tree at 0x02B21C60>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpq4bpije2'
Exception ignored in: <generator object get_tree at 0x02B21BE8>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpksdlx_uf'
Exception ignored in: <generator object get_tree at 0x02B21CB0>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree
  File "C:\Python34\lib\tempfile.py", line 687, in __exit__
  File "C:\Python34\lib\tempfile.py", line 693, in cleanup
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\dev\\dotfiles\\.peru\\tmp\\tmpifd5l99w'
Exception ignored in: <generator object get_tree at 0x02A95F80>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\peru\resolver.py", line 21, in get_tree
  File "C:\Python34\lib\site-packages\peru\remote_module.py", line 36, in get_tree

C:\dev\dotfiles>\Python34\Scripts\peru.exe synchg --repository C:\dev\dotfiles\.peru\cache\plugins\hg\a7567368584c40ffdd
```

After running that hg command manually, it completed fine and `peru sync` started working normally again except for this warning:

```
C:\dev\dotfiles>\Python34\Scripts\peru.exe sync --force
RuntimeError: <_overlapped.Overlapped object at 0x029D9E38> still has pending operation at deallocation, the process may
 crash
```

**Comment by oconnor663** [comment]
I'm going to close this for now, unless it's still an issue for you @edbrannin. We could consider implementing something where the hg/git plugins notice SSH urls and fail with a helpful error message. But I think some people are going to be in environments where they really need SSH, and if they're willing to jump through the hoops to make it Just Work then I don't want to stop them.
