### ISSUE TITLE
unknown module fields cause a nasty error

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#73]
```
Unknown module fields: untar
Task was destroyed but it is pending!
task: <Task pending coro=<get_tree() running at /usr/lib/python3.4/site-packages/peru/resolver.py:21> wait_for=<Future finished result=None> cb=[gather.<locals>._done_callback(0)() at /usr/lib/python3.4/asyncio/tasks.py:581]>
Exception ignored in: <generator object get_tree at 0x7f8a82e6a678>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/peru/resolver.py", line 21, in get_tree
  File "/usr/lib/python3.4/site-packages/peru/remote_module.py", line 36, in get_tree
  File "/usr/lib/python3.4/tempfile.py", line 691, in __exit__
  File "/usr/lib/python3.4/tempfile.py", line 697, in cleanup
  File "/usr/lib/python3.4/shutil.py", line 454, in rmtree
  File "/usr/lib/python3.4/shutil.py", line 452, in rmtree
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/f/.peru/tmp/tmpgy6li_et'
Task was destroyed but it is pending!
task: <Task pending coro=<get_tree() running at /usr/lib/python3.4/site-packages/peru/resolver.py:21> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(2)() at /usr/lib/python3.4/asyncio/tasks.py:581]>
Exception ignored in: <generator object get_tree at 0x7f8a82e6a708>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/peru/resolver.py", line 21, in get_tree
  File "/usr/lib/python3.4/site-packages/peru/remote_module.py", line 36, in get_tree
  File "/usr/lib/python3.4/tempfile.py", line 691, in __exit__
  File "/usr/lib/python3.4/tempfile.py", line 697, in cleanup
  File "/usr/lib/python3.4/shutil.py", line 454, in rmtree
  File "/usr/lib/python3.4/shutil.py", line 452, in rmtree
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/f/.peru/tmp/tmplzzifbmn'
```

**Comment by oconnor663** [comment]
Note that dcc1a69f7a891c19b0616c83de101681ebd15a82 added the decent error message that we see on the first line, but the garbage that follows after it is probably related to https://github.com/buildinspace/peru/issues/52.
